### ISSUE TITLE
Issues with numeric datatype

### ISSUE THREAD

**Issue by jimbobparsons** [mxmzdlv/pybigquery#38] opened 2019-08-19 00:40 UTC
Currently I trying to load data from a csv into Bigquery via pandas but am running into an issue with the Numeric datatype.

**standard.csv**

dt_INT,dt_string,dt_DATETIME,dt_timestamp,dt_date,dt_numeric,dt_time,dt_float,dt_bool
1,JIM,2019-07-01 23:59:29.01,2019-07-01 23:59:29.010000 UTC,2019-07-01,13.3,23:59:29.01,13.99999,TRUE
1,SHAN,2019-07-01 23:59:29.01,2019-07-01 23:59:29.010000 UTC,2019-07-01,13.2,23:59:29.01,13.99999,TRUE

**python_code**

import pandas as pd

import sqlalchemy

import os

engine = sqlalchemy.create_engine(f'bigquery://project_id')

dtypes = {

      'dt_INT': sqlalchemy.types.INTEGER(),

      'dt_string': sqlalchemy.types.VARCHAR(),

      'dt_DATETIME': sqlalchemy.types.DATETIME(),

      'dt_timestamp': sqlalchemy.types.TIMESTAMP(),

      'dt_date': sqlalchemy.types.DATE(),

      'dt_numeric': sqlalchemy.types.DECIMAL(),

      'dt_time': sqlalchemy.types.TIME(),

      'dt_float': sqlalchemy.types.FLOAT(),

      'dt_bool': sqlalchemy.types.BOOLEAN()

      }

df = pd.read_csv('GCP/standard.csv')

df.to_sql('SANDPIT.datatype_table', engine, if_exists='append', dtype=dtypes, index=False)

**error**

Traceback (most recent call last):

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 170, in execute

    self._query_job.result()

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/google/cloud/bigquery/job.py", line 2877, in result

    super(QueryJob, self).result(timeout=timeout)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/google/cloud/bigquery/job.py", line 733, in result

    return super(_AsyncJob, self).result(timeout=timeout)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/google/api_core/future/polling.py", line 127, in result

    raise self._exception

google.api_core.exceptions.BadRequest: 400 Value has type FLOAT64 which cannot be inserted into column dt_numeric, which has type NUMERIC at [1:230]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1224, in _execute_context

    cursor, statement, parameters, context

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 549, in do_executemany

    cursor.executemany(statement, parameters)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 188, in executemany

    self.execute(operation, parameters)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 172, in execute

    raise exceptions.DatabaseError(exc)

google.cloud.bigquery.dbapi.exceptions.DatabaseError: 400 Value has type FLOAT64 which cannot be inserted into column dt_numeric, which has type NUMERIC at [1:230]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/Users/parsonj3/Desktop/Learn/bqtest.py", line 22, in <module>

    df.to_sql('SANDPIT.datatype_table', engine, if_exists='append', dtype=dtypes, index=False)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/pandas/core/generic.py", line 2531, in to_sql

    dtype=dtype, method=method)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/pandas/io/sql.py", line 460, in to_sql

    chunksize=chunksize, dtype=dtype, method=method)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/pandas/io/sql.py", line 1174, in to_sql

    table.insert(chunksize, method=method)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/pandas/io/sql.py", line 686, in insert

    exec_insert(conn, keys, chunk_iter)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/pandas/io/sql.py", line 599, in _execute_insert

    conn.execute(self.table.insert(), data)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute

    return meth(self, multiparams, params)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection

    return connection._execute_clauseelement(self, multiparams, params)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement

    distilled_params,

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context

    e, statement, parameters, cursor, context

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception

    util.raise_from_cause(sqlalchemy_exception, exc_info)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause

    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise

    raise value.with_traceback(tb)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1224, in _execute_context

    cursor, statement, parameters, context

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 549, in do_executemany

    cursor.executemany(statement, parameters)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 188, in executemany

    self.execute(operation, parameters)

  File "/Users/parsonj3/Desktop/Learn/venv/lib/python3.7/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 172, in execute

    raise exceptions.DatabaseError(exc)

sqlalchemy.exc.DatabaseError: (google.cloud.bigquery.dbapi.exceptions.DatabaseError) 400 Value has type FLOAT64 which cannot be inserted into column dt_numeric, which has type NUMERIC at [1:230]

[SQL: INSERT INTO `SANDPIT.datatype_table` (`dt_INT`, `dt_string`, `dt_DATETIME`, `dt_timestamp`, `dt_date`, `dt_numeric`, `dt_time`, `dt_float`, `dt_bool`) VALUES (%(dt_INT)s, %(dt_string)s, %(dt_DATETIME)s, %(dt_timestamp)s, %(dt_date)s, %(dt_numeric)s, %(dt_time)s, %(dt_float)s, %(dt_bool)s)]

[parameters: ({'dt_INT': 1, 'dt_string': 'JIM', 'dt_DATETIME': '2019-07-01 23:59:29.01', 'dt_timestamp': '2019-07-01 23:59:29.010000 UTC', 'dt_date': '2019-07-01', 'dt_numeric': 13.3, 'dt_time': '23:59:29.01', 'dt_float': 13.999989999999999, 'dt_bool': True}, {'dt_INT': 1, 'dt_string': 'SHAN', 'dt_DATETIME': '2019-07-01 23:59:29.01', 'dt_timestamp': '2019-07-01 23:59:29.010000 UTC', 'dt_date': '2019-07-01', 'dt_numeric': 13.2, 'dt_time': '23:59:29.01', 'dt_float': 13.999989999999999, 'dt_bool': True})]

(Background on this error at: http://sqlalche.me/e/4xp6)

**Additional info**
On further debug it seems to be an issue with the BigQueryCompiler and the addition of a _bind_processors = {dict} <class 'dict'>: {'dt_numeric': <built-in function to_float>} which converts the numeric to a float.

If I execute if debug mode and slowly step over the code it works so thinking it might be some sort of timing issue.

**Comment by jimbobparsons** [comment] 2019-08-19 07:23
root cause is this flag not being set in BigQueryDialect

should be set: supports_native_decimal = True

otherwise bind_processor returns processors.to_float

sqltype.py
....
class Numeric(_LookupExpressionAdapter, TypeEngine):
...
	def bind_processor(self, dialect):
	    if dialect.supports_native_decimal:
	        return None
	    else:
	        return processors.to_float

**Comment by tswast** [comment] 2019-08-19 17:49
For loading data from CSV, I would strongly recommend using a load job rather than going through DML via SQLAlchemy, as you are limited in the number of DML queries you can perform per day and it's not possible to load as much data at once using INSERT queries, so you will hit those limits much sooner than you would hit the load job limits.

That said, thank you for the report and the investigation towards the root cause. I agree that this should be fixed.

**Closed** 2019-08-19 23:24 UTC
