### ISSUE TITLE
Trouble with parsing _TABLE_SUFFIX in Bigquery

### ISSUE THREAD

**Issue by jonyeo08** [mxmzdlv/pybigquery#1] opened 2017-09-07 20:25 UTC
Hi,

First, big thanks for making this! It really makes a world of a difference. 

I used pybigquery for Superset, a data viz tool from Airbnb. When I have DATETIME(TIMESTAMP(PARSE_DATE('%Y%m%d',_TABLE_SUFFIX))) AS dt, it works fine in SQL lab. But when I try to visualize, i get this error unsupported format character 'Y' (0x59) at index 111. Is there anyway around this?

I tried adding '%' to '%Y%m%d' but no luck. 
<img width="744" alt="screen shot 2017-09-07 at 1 32 07 pm" src="https://user-images.githubusercontent.com/9161092/30183907-01e3f55e-93d1-11e7-94a3-b721f78e5806.png">

Link to superset: https://github.com/apache/incubator-superset

**Comment by mxmzdlv** [comment] 2017-09-07 22:17
Hey, thanks for the report. I am currently in the process of replacing dbapi with the official Google's version, so I reckon it should be fixed in it. It'll be out in a few days.

**Comment by mxmzdlv** [comment] 2017-09-09 04:07
@jonyeo08 could you please try this again with the new pybigquery version? Also, try escaping percent signs like this: `%%Y%%m%%d`

**Comment by jonyeo08** [comment] 2017-09-09 09:12
Thanks for the quick response @mxmzdlv! I tried using '%%%' and '%%'

It looks like it gets confused whenever I have % in my query. This is the hack around I came up with: PARSE_DATETIME(REPLACE('_Y_m_d','_',CODE_POINTS_TO_STRING([37])),_TABLE_SUFFIX)

I hid the % lol

**Comment by jonyeo08** [comment] 2017-09-09 09:16
Sounds great!

**Comment by mxmzdlv** [comment] 2017-09-09 09:59
Nice hack. :) The problem is that the underlying DB-API is trying to format the query using python's `%` operator. I've just replicated the issue with Superset and escaping %'s like this `%%Y%%m%%d` worked for me, at least with the new pybigquery.

**Comment by jonyeo08** [comment] 2017-09-12 00:24
Interesting! Thanks @mxmzdlv. Maybe the newest version will fix things. I'll take a look and report back here.

**Closed** 2018-05-24 01:05 UTC
